### PR TITLE
Stack names and Resource Groups in Azure

### PR DESCRIPTION
**Pull request by russellseymour**
Moved the creation of the ResourceGroup in Azure to the common library so it can be reused.

Added a `--config` option to the deploy command so that the correct YAML file is used when creating the ResoureGroup as this will contain the location.

A resource group with a suffix will be created for each deployment made in Wombat.  This can be overridden with a new option on the command line `--nosuffix`.

The `output` command now lists all the resource groups that start with the name of the stack.  This is so that the name of a resource group to delete can be determined.

The `delete` command will now delete the selected resource group in its entirety.  If the parent group (as named as the name in the `wombat.yml`) a warning will be displayed and it will not be deleted unless the `--force` option is specified.

Another switch has been added to the deploy command (`-n`, `--name`) which allows for a one off creation of a completely different stack in Azure.  The code _should_ work in AWS as well because it is just a simple change of the stack name.

```
wombat deploy -n acceptance-rjs-demo bjc-demo
```

/cc @bakh @scarolan

### CODE REVIEW

**Comment by scarolan** [comment]
:excellent: :shipit: 👍

**Comment by binamov** [comment]
i built the gem off this branch and tried it:
```
λ  wombat deploy -c azure bjc-demo
==> Creating Azure RM stack
==> Checking for resource group: bjc-demo-20170411130239
creating new resource group in 'westus'
>>> {
  "message": "MsRestAzure::AzureOperationError: DeploymentNotFound: Deployment 'deploy-1491940959' could not be found.",
  "request": {
    "base_uri": "https://management.azure.com",
    "path_template": "/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/deployments/{deploymentName}/operations",
    "method": "get",
    "path_params": {
      "resourceGroupName": "bjc-demo",
      "deploymentName": "deploy-1491940959",
      "subscriptionId": "1e0b427a-d58b-494e-ae4f-ee558463ebbf"
    },
    "skip_encoding_path_params": null,
    "query_params": {
      "$top": null,
      "api-version": "2016-09-01"
    },
    "skip_encoding_query_params": null,
    "headers": {
      "Content-Type": "application/json;charset=utf-8",
      "accept-language": "en-US",
      "x-ms-client-request-id": "3b8ea456-2489-41df-a8fc-07ea4eaf083b"
    },
    "body": null,
    "middlewares": [
      [
        "MsRest::RetryPolicyMiddleware",
        {
          "times": 3,
          "retry": 0.02
        }
      ],
      [
        "cookie_jar"
      ]
    ],
    "log": null
  },
  "response": {
    "body": "{\"error\":{\"code\":\"DeploymentNotFound\",\"message\":\"Deployment 'deploy-1491940959' could not be found.\"}}",
    "headers": {
      "cache-control": "no-cache",
      "pragma": "no-cache",
      "content-type": "application/json; charset=utf-8",
      "expires": "-1",
      "x-ms-failure-cause": "gateway",
      "x-ms-ratelimit-remaining-subscription-reads": "14983",
      "x-ms-request-id": "1e753d46-db93-4467-9f3b-8c5f9fafdb04",
      "x-ms-correlation-request-id": "1e753d46-db93-4467-9f3b-8c5f9fafdb04",
      "x-ms-routing-request-id": "CANADAEAST:20170411T200249Z:1e753d46-db93-4467-9f3b-8c5f9fafdb04",
      "strict-transport-security": "max-age=31536000; includeSubDomains",
      "date": "Tue, 11 Apr 2017 20:02:48 GMT",
      "connection": "close",
      "content-length": "102"
    },
    "status": 404
  }
}
```

also this:
```
λ  wombat deploy -c azure -n bakh-test-bjc-demo bjc-demo
==> Creating Azure RM stack
==> Checking for resource group: bakh-test-bjc-demo-20170411130148
creating new resource group in 'westus'
>>> {
  "message": "MsRestAzure::AzureOperationError: ResourceGroupNotFound: Resource group 'bakh-test-bjc-demo' could not be found.",
  "request": {
    "base_uri": "https://management.azure.com",
    "path_template": "/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/deployments/{deploymentName}/operations",
    "method": "get",
    "path_params": {
      "resourceGroupName": "bakh-test-bjc-demo",
      "deploymentName": "deploy-1491940908",
      "subscriptionId": "1e0b427a-d58b-494e-ae4f-ee558463ebbf"
    },
    "skip_encoding_path_params": null,
    "query_params": {
      "$top": null,
      "api-version": "2016-09-01"
    },
    "skip_encoding_query_params": null,
    "headers": {
      "Content-Type": "application/json;charset=utf-8",
      "accept-language": "en-US",
      "x-ms-client-request-id": "a4cb584d-e460-4fc4-8485-b6bec9505695"
    },
    "body": null,
    "middlewares": [
      [
        "MsRest::RetryPolicyMiddleware",
        {
          "times": 3,
          "retry": 0.02
        }
      ],
      [
        "cookie_jar"
      ]
    ],
    "log": null
  },
  "response": {
    "body": "{\"error\":{\"code\":\"ResourceGroupNotFound\",\"message\":\"Resource group 'bakh-test-bjc-demo' could not be found.\"}}",
    "headers": {
      "cache-control": "no-cache",
      "pragma": "no-cache",
      "content-type": "application/json; charset=utf-8",
      "expires": "-1",
      "x-ms-failure-cause": "gateway",
      "x-ms-ratelimit-remaining-subscription-reads": "14980",
      "x-ms-request-id": "96fddf9c-bea1-43f9-8cfd-0f199425bb13",
      "x-ms-correlation-request-id": "96fddf9c-bea1-43f9-8cfd-0f199425bb13",
      "x-ms-routing-request-id": "CANADAEAST:20170411T200159Z:96fddf9c-bea1-43f9-8cfd-0f199425bb13",
      "strict-transport-security": "max-age=31536000; includeSubDomains",
      "date": "Tue, 11 Apr 2017 20:01:59 GMT",
      "connection": "close",
      "content-length": "110"
    },
    "status": 404
  }
}
```
and this:
```
λ  wombat deploy -c azure --nosuffix -n bakh-tester-bjc-demo bjc-demo
==> Creating Azure RM stack
==> Checking for resource group: bakh-tester-bjc-demo-20170411132532
creating new resource group in 'westus'
>>> {
  "message": "MsRestAzure::AzureOperationError: ResourceGroupNotFound: Resource group 'bakh-tester-bjc-demo' could not be found.",
  "request": {
    "base_uri": "https://management.azure.com",
    "path_template": "/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/deployments/{deploymentName}/operations",
    "method": "get",
    "path_params": {
      "resourceGroupName": "bakh-tester-bjc-demo",
      "deploymentName": "deploy-1491942332",
      "subscriptionId": "1e0b427a-d58b-494e-ae4f-ee558463ebbf"
    },
    "skip_encoding_path_params": null,
    "query_params": {
      "$top": null,
      "api-version": "2016-09-01"
    },
    "skip_encoding_query_params": null,
    "headers": {
      "Content-Type": "application/json;charset=utf-8",
      "accept-language": "en-US",
      "x-ms-client-request-id": "7805912c-31f8-44e6-be4a-d8f1c09f3109"
    },
    "body": null,
    "middlewares": [
      [
        "MsRest::RetryPolicyMiddleware",
        {
          "times": 3,
          "retry": 0.02
        }
      ],
      [
        "cookie_jar"
      ]
    ],
    "log": null
  },
  "response": {
    "body": "{\"error\":{\"code\":\"ResourceGroupNotFound\",\"message\":\"Resource group 'bakh-tester-bjc-demo' could not be found.\"}}",
    "headers": {
      "cache-control": "no-cache",
      "pragma": "no-cache",
      "content-type": "application/json; charset=utf-8",
      "expires": "-1",
      "x-ms-failure-cause": "gateway",
      "x-ms-ratelimit-remaining-subscription-reads": "14985",
      "x-ms-request-id": "8e8cdf51-de4f-4589-aa48-0a55b1fbe5a2",
      "x-ms-correlation-request-id": "8e8cdf51-de4f-4589-aa48-0a55b1fbe5a2",
      "x-ms-routing-request-id": "CANADAEAST:20170411T202542Z:8e8cdf51-de4f-4589-aa48-0a55b1fbe5a2",
      "strict-transport-security": "max-age=31536000; includeSubDomains",
      "date": "Tue, 11 Apr 2017 20:25:42 GMT",
      "connection": "close",
      "content-length": "112"
    },
    "status": 404
  }
}
```

**Comment by russellseymour** [comment]
@binamov This occurs when the `--async` option is not used.

In this scenario `wombat` will try to check the status of the deployment for you, but it is not getting the name of the deployment correctly because I missed changing a variable in the code.  My tests were obviously only done with this argument.

The deployment is running OK in Azure, but you are not getting the feedback on the command line.

I will sort it out.

**Comment by binamov** [comment]
thanks for the fixes! still got a bug where `wombat deploy -c azure --nosuffix -n bakh-test-bjc-demo bjc-demo` produces a suffixed rg @russellseymour

**Comment by russellseymour** [comment]
@binamov All fixed

Using the `-n` option now implies `--nosuffix`
Also corrected an issue where the cli was not setting the `nosuffix` property as it was not named correctly ... DOH!

**Comment by binamov** [comment]
sweet! 🍨

**Pull request merged**
